### PR TITLE
added events for everything

### LINKED ISSUE #2: Is there a way to get realtime stats?
Is there a way to get realtime stats? Altitude, Speed...

### PR DESCRIPTION
**Pull request by johan-olsson**
I converted https://github.com/Parrot-Developers/libARCommands/blob/master/Xml/ARDrone3_commands.xml and https://github.com/Parrot-Developers/libARCommands/blob/master/Xml/common_commands.xml to json and use them to create events for everything that's coming in. 

The only limitation really is that the event names will be the same as in the spec for example the "battery" event would be called "BatteryStateChanged". But then again it also means that we get some free documentation from them :)

close #2 #11

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi, @johan-olsson this is really awesome!

You might have noticed that the Travis tests failed. It is due to the ESLint failing on the new code: https://travis-ci.org/hybridgroup/node-bebop/jobs/91291577

Can you please help resolve these? I think it could be done easily if you made a couple small mods to your generator script (I assume you did this with a script?)

**Comment by johan-olsson** [comment]
I think there should be running better on travis now.

**Comment by deadprogram** [comment]
That corrected the linter complaints win commands, but there are still a few more in the other files:
https://travis-ci.org/hybridgroup/node-bebop/jobs/91313694

**Comment by johan-olsson** [comment]
Ah weird. Didn't touch some of those files, I'll take a look tomorrow. It's almost 5:30 here after all.

**Comment by deadprogram** [comment]
A bunch of those warnings have been there for a while. The error that is causing eslint to fail is:

```
lib/bebop.js
  13:1  error  Unexpected token function
```

**Comment by johan-olsson** [comment]
Think there is some bisection mistakes. I'll push some fixes when I feel the different versions are stable enough

**Comment by deadprogram** [comment]
Thanks!

**Comment by johan-olsson** [comment]
I have tested most of this. But it's a bit to windy to be able to test everything. I'll have to wait until spring to have the outdoor stuff down.

**Comment by deadprogram** [comment]
This is pretty awesome stuff, sorry it has taken so long to look deeply into it. @johan-olsson could you please add some of your test code as examples? I think it would be super helpful.

**Comment by deadprogram** [comment]
HIm @johan-olsson the events seem to be coming thru, but I just tried to call one of the new commands and it did not work as expected:

```
$ node examples/gps.js 
buffer.js:829
    throw new TypeError('value is out of bounds');
    ^

TypeError: value is out of bounds
    at checkInt (buffer.js:829:11)
    at Buffer.writeUInt16LE (buffer.js:887:5)
    at Object.module.exports.u16.write (/home/ron/Development/node-bebop/lib/types.js:29:14)
    at /home/ron/Development/node-bebop/lib/commandToBuffer.js:58:23
    at Array.forEach (native)
    at writeBuffer (/home/ron/Development/node-bebop/lib/commandToBuffer.js:56:11)
    at module.exports (/home/ron/Development/node-bebop/lib/commandToBuffer.js:67:10)
    at Object.Bebop.GPSSettings.ResetHome (/home/ron/Development/node-bebop/lib/bebop.js:650:16)
    at /home/ron/Development/node-bebop/examples/gps.js:36:21
    at null.<anonymous> (/home/ron/Development/node-bebop/lib/bebop.js:180:7)
```

The code was:

```
var bebop = require("../.");

var drone = bebop.createClient();

drone.connect(function() {
  drone.on("ready", function(){
    console.log("ready");
  });

  drone.on("GPSFixStateChanged", function(data){
    console.log("GPSFixStateChanged", data);
  })

  drone.on("GPSUpdateStateChanged", function(data){
    console.log("GPSUpdateStateChanged", data);
  });

  drone.on("GPSSettingsState", function(data){
    console.log("GPSSettingsState", data);
  });

  drone.on("GPSState", function(data){
    console.log("GPSState", data);
  });


  drone.GPSSettings.ResetHome()
});

```

Am I missing something here?

**Comment by deadprogram** [comment]
Hi, @johan-olsson did you see my last comment?

**Comment by johan-olsson** [comment]
Yeah, I started looking in to it but ran out of battery. I'll be back on it later tonight. Should be a quite easy fix.

**Comment by deadprogram** [comment]
:bow:

**Comment by johan-olsson** [comment]
Hey @deadprogram, I remember what the issue was now. I was running my test on a version with flat namespaces since I can't access the drone `this` from `drone.GPSSettings.ResetHome` without restructuring the entire file. Sorry for all the confusion, to many projects on the go at the moment. What do you think?

**Comment by deadprogram** [comment]
Sorry, can you please show me example of code you have that works? Perhaps I can help you get `this` in scope.

**Comment by johan-olsson** [comment]
Alright, So this would work.
```JavaScript
Bebop.prototype.GPSSettingsResetHome = function() {

  var buffer = commandToBuffer(1, "GPSSettings", "ResetHome");

  this._writePacket(this._networkFrameGenerator(buffer));
  return this;
};
```

While I can't get this to work
```JavaScript
Bebop.prototype.GPSSettings = {};
Bebop.prototype.GPSSettings.ResetHome = function() {

  var buffer = commandToBuffer(1, "GPSSettings", "ResetHome");

  this._writePacket(this._networkFrameGenerator(buffer));
  return this;
};
```

**Comment by deadprogram** [comment]
Thanks for elaborating. Actually there were 2 problems, one being the wrong parameter being passed to the `commandToBuffer` function.

Yes, your problem is `this` always refers to the object to which the function belongs. You really want the parent.

What I personally would suggest, would be to refactor the code to separate out the various interfaces. I've taken the liberty of creating a branch that shows what I mean https://github.com/hybridgroup/node-bebop/tree/features/separate-interfaces

If that looks good to you, perhaps you would like to update your branch accordingly?

I have still yet to get the GPS events to be returned, but this is I think at least code that executes correctly.

**Comment by deadprogram** [comment]
One other small, but probably important thing to note: functions that are not constructors, should not start with upper case. I changed some signatures for example https://github.com/hybridgroup/node-bebop/blob/features/separate-interfaces/lib/gpssettings.js#L9 `Bebop.GPSSettings.SetHome()` is now `Bebop.GPSSettings.setHome()`.

**Comment by deadprogram** [comment]
Hi, @johan-olsson did you see my last couple of comments?

**Comment by johan-olsson** [comment]
Ah yeah, it looks nice. I'm working on a script to generate that

**Comment by deadprogram** [comment]
:dizzy:

**Comment by deadprogram** [comment]
Hi, @johan-olsson anything I can do to help? I really really want this! :baby:

**Comment by johan-olsson** [comment]
Ah sorry mate been a bit occupied. I'll try to focus a bit more on getting this finished

**Comment by johan-olsson** [comment]
[This](https://github.com/johan-olsson/node-bebop/commit/58c8ac07ff9a473d2cd4d285b2091012b3f01ce8) is kind of what you had in mind?

**Comment by johan-olsson** [comment]
Yeah I'm working on some of the lint issues now

**Comment by johan-olsson** [comment]
Alright, all test seems to be passing now. But I haven't really had any opportunity to test anything yet

**Comment by deadprogram** [comment]
This really looks incredible. I'll do some testing myself, and also try to recruit a couple others to look at it.

**Comment by deadprogram** [comment]
Hi, @johan-olsson I had a chance to do some testing. Here is what I have found so far.

My initial test program is:
```
"use strict";

var bebop = require("../.");

var drone = bebop.createClient();

drone.connect(function() {
  drone.Piloting.takeOff();

  setTimeout(function() {
    drone.Piloting.landing();
  }, 5000);
});
```

First I tried just exercising the `Piloting` interface. It still seems to have the wrong value for the first param being passed to `commandToBuffer`. If I change https://github.com/johan-olsson/node-bebop/blob/master/lib/Piloting.js#L21 to `var buffer = commandToBuffer(1, "Piloting", "TakeOff");` it flies. Likewise https://github.com/johan-olsson/node-bebop/blob/master/lib/Piloting.js#L37 needs the same change.

OK, next I tried to add the `Headlights` interface.

```
"use strict";

var bebop = require("../.");

var drone = bebop.createClient();

drone.connect(function() {
  drone.Piloting.takeOff();
  drone.Headlights.intensity({left: 255, right: 255});

  setTimeout(function() {
    drone.Piloting.landing();
    drone.Headlights.intensity({left: 128, right: 128});
  }, 5000);
});
```

I tried making various changes to the first param, but I always get an error like this:
```
$ node examples/piloting.js 
buffer.js:829
    throw new TypeError('value is out of bounds');
    ^

TypeError: value is out of bounds
    at checkInt (buffer.js:829:11)
    at Buffer.writeUInt16LE (buffer.js:887:5)
    at Object.module.exports.u16.write (/home/ron/Development/node-bebop/lib/types.js:29:14)
    at /home/ron/Development/node-bebop/lib/commandToBuffer.js:59:23
    at Array.forEach (native)
    at writeBuffer (/home/ron/Development/node-bebop/lib/commandToBuffer.js:57:11)
    at module.exports (/home/ron/Development/node-bebop/lib/commandToBuffer.js:68:10)
    at Headlights.intensity (/home/ron/Development/node-bebop/lib/Headlights.js:13:16)
    at /home/ron/Development/node-bebop/examples/piloting.js:9:20
    at null.<anonymous> (/home/ron/Development/node-bebop/lib/bebop.js:255:7)
```

I'm not sure what needs to be passed into the `Headlights.intensity()` function. It would be spectacular if the info you added to the README.md was added to each interface function as a code comment, ideally in JSDoc format.

**Comment by johan-olsson** [comment]
It actually worked for me when I changed my Headlights.js one to 0 instead of 1. Seems like they got reversed

**Comment by deadprogram** [comment]
Yes, that did it!

For example: I was just able to get GPS data:

```
"use strict";

var bebop = require("../.");

var drone = bebop.createClient();

drone.connect(function() {
  drone.GPSSettings.resetHome();
  drone.WifiSettings.outdoorSetting(1);

  drone.on("PositionChanged", function(data) {
    console.log(data);
  })
});
```

Resulted in this output:
```
$ node examples/gps.js
{ latitude: 34.08478202515631,
  longitude: -118.27801833333642,
  altitude: 0 }
{ latitude: 34.08478202515631,
  longitude: -118.27802000000315,
  altitude: 0 }
{ latitude: 34.08478202515631,
  longitude: -118.27802000000315,
  altitude: 0 }
{ latitude: 34.08478202515631,
  longitude: -118.27801833333642,
  altitude: 0 }
{ latitude: 34.08478202515631,
  longitude: -118.27801333333106,
  altitude: 0 }
```

**Comment by johan-olsson** [comment]
Awesome stuff :)

**Comment by leerlemoniii** [comment]
This looks amazing, can not wait to build this branch, and try it out.... how soon will this be merged to master?

**Comment by johan-olsson** [comment]
I haven't been able to test it in action to much yet since I still can't fly outside over here. @deadprogram might have had some better luck with the weather since he is from LA, at least according to his drones coordinates ;)

**Comment by deadprogram** [comment]
I will charge up some batteries and do some flight tests today, so we can get this out!

**Comment by deadprogram** [comment]
When running the gps.js example, I get the following error using node 0.10.40:

```
$ node examples/gps.js 

buffer.js:705
    throw TypeError('value is out of bounds');
          ^
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:705:11)
    at Buffer.writeUInt8 (buffer.js:715:5)
    at Object.module.exports.u8.write (/home/ron/Development/node-bebop/lib/types.js:9:14)
    at /home/ron/Development/node-bebop/lib/commandToBuffer.js:59:23
    at Array.forEach (native)
    at writeBuffer (/home/ron/Development/node-bebop/lib/commandToBuffer.js:57:11)
    at module.exports (/home/ron/Development/node-bebop/lib/commandToBuffer.js:68:10)
    at WifiSettings.outdoorSetting (/home/ron/Development/node-bebop/lib/WifiSettings.js:13:16)
    at /home/ron/Development/node-bebop/examples/gps.js:9:22
```

Then I loaded Node 4.2.2, installed all the npm modules, it does not crash. At first, I was not getting valid data:

```
$ node examples/gps.js 
{ latitude: 500, longitude: 500, altitude: 500 }
{ latitude: 500, longitude: 500, altitude: 500 }
{ latitude: 500, longitude: 500, altitude: 500 }
{ latitude: 500, longitude: 500, altitude: 500 }
{ latitude: 500, longitude: 500, altitude: 500 }
{ latitude: 500, longitude: 500, altitude: 500 }
{ latitude: 500, longitude: 500, altitude: 500 }
{ latitude: 500, longitude: 500, altitude: 500 }
{ latitude: 500, longitude: 500, altitude: 500 }
```

I then ran the FreeFlight 3 mobile app, and after that the node program started returning the GPS coordinates as expected. Seems like there must be some additional initialization we need to send to get the GPS started.

In any case, @johan-olsson what do you think about this? Many people still have node 0.10.x installed.

**Comment by deadprogram** [comment]
When running under node 0.10.x If I remove the line `drone.WifiSettings.outdoorSetting(1);` from the gps.js example above, I still get errors:

```
$ node examples/gps.js 
{ latitude: 34.084781666666196,
  longitude: -118.27799000000253,
  altitude: 0 }

/home/ron/Development/node-bebop/lib/bebop.js:309
      .first({_id: commandProject}).class
                                   ^
TypeError: Cannot read property 'class' of null
    at Bebop._packetReceiver (/home/ron/Development/node-bebop/lib/bebop.js:309:36)
    at Socket.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:441:8)
```

**Comment by deadprogram** [comment]
OK yet *more* info :)

Looks like the above error is what happens when a new packet type comes back from the Bebop, having nothing to do with Node version. 

I updated the firmware to 2.0.57, and now there is a value with `commandProject:129` and 'commandClass:3` being returned.

**Comment by deadprogram** [comment]
Hi, @johan-olsson did you see my comment above regarding a problem when an unknown command packet is returned by the Bebop?

**Comment by johan-olsson** [comment]
Hmm it really look like it. I'll take a look at there new docs

**Comment by deadprogram** [comment]
Should probably put in some code to handle when new unknown messages come in and ignore them, so we can handle new minor firmware updates more easily.

Thank you so much @johan-olsson for all your work on this, it is so cool. I'm excited to released once ready.

**Comment by johan-olsson** [comment]
I added the new stuff to the command file and also added a way to update it when needed.

**Comment by deadprogram** [comment]
Seems like this line https://github.com/johan-olsson/node-bebop/blob/master/lib/bebop.js#L342 is no longer emitting events correctly. I think `event._name` is now `event.name`. Also `args` is always empty.

**Comment by johan-olsson** [comment]
Hmm alright. I'll update my drone and see what I can find out

**Comment by deadprogram** [comment]
Also, looks like for versions of Node >= 4.x you now need the following added to the .travis.yml file, so that the xml2json package can build:

```
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
```

**Comment by johan-olsson** [comment]
That should do it.

**Comment by deadprogram** [comment]
The GPS lock problem is not related to anything we seem to be doing from the API. In any case, the event is returning valid formatting for the data. I think we're ready to merge!

**Comment by johan-olsson** [comment]
Hurray! :tada:

**Comment by nelson-liu** [comment]
@deadprogram would you mind posting the contents of examples/gps.js? I'm a bit confused as to which function I should be calling to get the gps coordinates of the drone. Would it be GPSSettings.sendControllerGPS(obj)?

**Comment by nelson-liu** [comment]
@deadprogram how did you solve the issue where the GPS was returning just 
{ latitude: 500, longitude: 500, altitude: 500 } over and over again? I tried running the freeflight app, connecting to the drone, and entering free flight (but not actually launching the drone). After doing so, my script (the same as the one you put above) would not even output anything.

**Comment by deadprogram** [comment]
@nelson-liu I do not yet have a firm grasp over why the Bebop was taking so long to get a satellite lock. This thread from the Parrot forum is very interesting, many Bebop users have had similar troubles: http://forum.parrot.com/usa/viewtopic.php?id=30757

**Pull request merged**
